---
driver:
  name: vagrant

provisioner:
  product_name: chef
  product_version: 12

platforms:
  - name: ubuntu-16.04
  - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[sockd::default]
    attributes: {
    }
